names = ['Mr. Teacher', 'Antonio Banderas', 'Cynthia Erivo',
'Juliane Baham', 'Shiloh Mease', 'Karry Quinn',
'Shiloh Mease', 'Karry Quinn', 'Alica Hiebert',
'Karry Quinn', 'Alica Hiebert', 'Marquitta Klick',
'Alica Hiebert', 'Marquitta Klick', 'Jame Carrier',
'Marquitta Klick', 'Jame Carrier', 'Mai Brouwer',
'Jame Carrier', 'Mai Brouwer', 'Josefina Tejeda',
'Mai Brouwer', 'Josefina Tejeda', 'Caroyln Fitzhenry',
'Josefina Tejeda', 'Caroyln Fitzhenry', 'Shamika Vang',
'Caroyln Fitzhenry', 'Shamika Vang', 'Kathrin Barnette',
'Shamika Vang', 'Kathrin Barnette', 'Erwin Loll',
'Kathrin Barnette', 'Erwin Loll', 'Celeste Larock',
'Erwin Loll', 'Celeste Larock', 'Ramonita Memmott',
'Celeste Larock', 'Ramonita Memmott', 'Ava Harth',
'Ramonita Memmott', 'Ava Harth', 'September Schiro',
'Ava Harth', 'September Schiro', 'Shelly Gargiulo',
'September Schiro', 'Shelly Gargiulo', 'Diamond Mckain',
'Shelly Gargiulo', 'Diamond Mckain', 'Evelia Wiggin',
'Diamond Mckain', 'Evelia Wiggin', 'Alaine Lenox',
'Evelia Wiggin', 'Alaine Lenox', 'Jenice Yarbrough',
'Alaine Lenox', 'Jenice Yarbrough', 'Casie Cropp',
'Jenice Yarbrough', 'Casie Cropp', 'Cathy Malpass',
'Casie Cropp', 'Cathy Malpass', 'Vida Eleby',
'Cathy Malpass', 'Vida Eleby', 'Marline Falbo',
'Vida Eleby', 'Marline Falbo', 'Merideth Koenen',
'Marline Falbo', 'Merideth Koenen', 'Rodney Landy',
'Merideth Koenen', 'Rodney Landy', 'Winston Rendell',
'Rodney Landy', 'Winston Rendell', 'Jodie Holmstrom',
'Winston Rendell', 'Jodie Holmstrom', 'Tad Cary',
'Jodie Holmstrom', 'Tad Cary', 'Jolynn Rhoads',
'Tad Cary', 'Jolynn Rhoads', 'Delmy Kaup',
'Jolynn Rhoads', 'Delmy Kaup', 'Versie Pane',
'Delmy Kaup', 'Versie Pane', 'Barney Gorham',
'Versie Pane', 'Barney Gorham', 'Minna Lopinto',
'Barney Gorham', 'Minna Lopinto', 'Woodrow Ballew',
'Minna Lopinto', 'Woodrow Ballew', 'Taina Marston',
'Woodrow Ballew', 'Taina Marston', 'Shondra Skelly',
'Taina Marston', 'Shondra Skelly', 'Irena Molyneux',
'Shondra Skelly', 'Irena Molyneux', 'Carey Cass',
'Irena Molyneux', 'Carey Cass', 'Enda Mandujano',
'Carey Cass', 'Enda Mandujano', 'Joette Ange',
'Enda Mandujano', 'Joette Ange', 'Sophia Lewicki',
'Joette Ange', 'Sophia Lewicki', 'Selena Olague',
'Sophia Lewicki', 'Selena Olague', 'Hermelinda Crosier',
'Selena Olague', 'Hermelinda Crosier', 'Marlana Ingle',
'Hermelinda Crosier', 'Marlana Ingle', 'Waldo Durio',
'Marlana Ingle', 'Waldo Durio', 'Marty Cassinelli',
'Waldo Durio', 'Marty Cassinelli', 'Celesta Southwood',
'Marty Cassinelli', 'Celesta Southwood', 'Angella Falco',
'Celesta Southwood', 'Angella Falco', 'Latoyia Stricklin',
'Angella Falco', 'Latoyia Stricklin', 'Emerald Pinelli']

names.each_with_index {|name, i|
  uid = sprintf "user%03d", i
  User.create(username: uid, fullname: name, password: '123456',
  role: ((i==0) ? :teacher : :student))
}